#!/usr/bin/env bash
## help sh/all : : show all the the local functions
Here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bold=$(tput bold)
col0=$(tput sgr0)
col1=$(tput setaf 6)  # cyan
echo "${bold}${col1}🚀 Commands:${col0}"

gawk -F: 'sub(/^## help /,""){ \
              printf "  \033[33m%10s\033[0m %-6s : %s\n",$1,$2,$3 \
         }' $Here/*

