#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
  
hi() { 
  tput bold; tput setaf 5
  cat<<-'EOF'
            _        __ __
 / _/ _    (_   /  /(  /__)
(()/_)   ()/   (__(__)/

(quote 
   (Elegant (weapons
      (for (a (more 
         (civilized age)))))))
                     
	EOF
  tput bold; tput setaf 241
  echo "Short cuts:"
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}
md2lisp() {
  mkdir -p $Ful/docs
  mkdir -p $Ful/.var
  local here=$PWD
  cd $Ful/docs
  for f in *.md; do
    g=${f%.md}.lisp
    cat $f | gawk '
       NR==1 { next }
       gsub(/^```.*/,"") {Code = 1 - Code; next}
                         {print (Code ? "" : "; ") $0}         
    '> $Ful/.var/$g
  done
  cd $here
}

if [ -z "$Ful" ]; then
  Ful="$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )"
  Ful="$Ful" bash --init-file "${BASH_SOURCE[0]}" -i
else
  mkdir -p $Ful/docs
  mkdir -p $Ful/.var
  alias ..='cd ..'
  alias ...='cd ../../../'

  alias bye="gp; tmux detach"
  alias egrep='egrep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias gp="git add *;git commit -am save;git push;git status"
  alias grep='grep --color=auto'
  alias h="history"
  alias hello="git pull"
  alias ls="ls -G"
  alias repl="rlwrap sbcl --noinform " 
  alias tmux="tmux -f $Ful/etc/dottmux "
  alias vi="vim -u $Ful/etc/dotvimrc "
  alias vims="vim +PluginInstall +qall"         

  lisp()  {
    local here=$PWD
    md2lisp
    f=$1
    shift
    cd $Ful/.var
    sbcl --noinform --script $f  $* 2> >( gawk ' {print} /^5:/ {exit}' ) 
    cd $here
  }
  
  here() { cd $1; basename `pwd`; }
  
  PROMPT_COMMAND='echo -ne "🧠 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
  hi
fi
