#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
  
hi() { 
  tput bold; tput setaf 5
  cat<<-'EOF'

  /')       /(    )\.--.     /`-.     
 ( /       \  )  (   ._.'   / _  \    
  ))       ) (    `-.`.    ( '-' (    
  )'._.-.  \  )  ._ (  \   ) .._.'    
 (       )  ) \ (  '.)  ) (  '        
  )/.___/    )/  '._.__/   )/         

 (quote
    (an (elegant (weapon 
        (for (a (more 
            (civilized age))))))))
                       
	EOF
  tput bold; tput setaf 241
  echo "Short cuts:"
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}

if [ -z "$timmLispFul" ]; then
  timmLispFul="$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )"
  PATH="$PATH:/opt/homebrew/bin" timmLispFul="$timmLispFul" bash --init-file "${BASH_SOURCE[0]}" -i
else
  alias ..='cd ..'
  alias ...='cd ../../../'

  alias bye="gp; tmux detach"
  alias ynot="lisp ynot.lisp "
  alias bnb="lisp bnb.lisp "
  alias egrep='egrep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias gp="git add *;git commit -am save;git push;git status"
  alias grep='grep --color=auto'
  alias h="history"
  alias keys="lisp keys.lisp "
  alias hello="git pull"
  alias ls="ls -G"
  alias sbcl="sbcl --noinform --script "
  alias repl="rlwrap sbcl --noinform " 
  alias tmux="/opt/homebrew/bin/tmux -f $timmLispFul/etc/dottmux "
  alias vi="vim -u $timmLispFul/etc/dotvimrc "
  alias macs="emacs   --load \"$here/etc/.spacemacs\" "
  alias vims="vim +PluginInstall +qall"         

  mkdir -p $timmLispFul/docs

  htmls() {  
    (cd $timmLispFul/src
    for i in *.lisp
    do
       doc $i
    done
    )
  }
  doc() {  
      (cat $timmLispFul/README.md | gawk '
            BEGIN { FS="\n"; RS="" }
                  { print  $0 "\n"; exit}' |
       gawk '{print "; " $0}
             END {print("\n\n;\n\n")}'  
      cat $1 | gawk '
      BEGIN {FS="\n";RS=""}
      NR==1 { print("\n\n"); next}
            {print $0 ""}'
      ) > $timmLispFul/docs/$1
      (cd $timmLispFul/docs; docco  -o . $1) 
      cp $timmLispFul/etc/docco.css $timmLispFul/docs
  }
  lisp()  {
    f=$1
    shift
    $(which sbcl) --noinform --script $f  $* \
         2> >( gawk '/^Backtrace / {exit} 1' ) 
  }
  
  here() { cd $1; basename `pwd`; }

export BASH_SILENCE_DEPRECATION_WARNING=1

  PROMPT_COMMAND='echo -ne "🚀 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
  hi
fi
