#!/usr/bin/env bash
## help sh/ow : x : make pretty doc from code file x
Here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pdf="$HOME/tmp/$(basename "${1%.*}").pdf"
html="$Here/../docs/$(basename "${1%.*}").html"

badges='
<a href="https://en.wikipedia.org/wiki/Explainable_artificial_intelligence"><img
   src="https://img.shields.io/badge/for-AI,XAI-blue?xstyle=flat&"></a>
<a href="https://gigamonkeys.com/book/introduction-why-lisp"><img
   src="https://img.shields.io/badge/uses-Lisp-purple.svg?xstyle=for-the-badge"
   alt="Language"></a>
<a href="https://github.com/timm/lisp"><img
   src="https://img.shields.io/badge/src-code-orange.svg?xstyle=for-the-badge"
   alt="Source Code"></a>
<a href="https://github.com/timm/lisp/blob/main/LICENSE.md"><img
   src="https://img.shields.io/badge/&copy;2025-MIT-brightgreen.svg?xstyle=for-the-badge"
   alt="License"></a>
'

pycco -l scheme -d $Here/../docs $1
cat<<-'EOF' >> $Here/../docs/pycco.css
div.docs {
  max-width: 350px !important;
  min-width: 350px !important; }

div.code    { margin-left: 430px !important; }
#background { left: 430px !important; }
h3          { text-align: right; }
p           { text-align: right; }
EOF

#
# echo "pdf-ing $pdf ... "
# a2ps                        \
#   --file-align=virtual       \
# 	--line-numbers=1            \
# 	--pro=color                  \
# 	--pretty=python               \
# 	--chars-per-line=70            \
# 	--left-title=""                 \
# 	--borders=no                     \
#   --right-footer="page %s. of %s#"  \
# 	--portrait                         \
# 	--columns 2                         \
# 	-M letter                            \
# 	-o - $1 | ps2pdf - $pdf

for f in $Here/../docs/*.html; do
  gawk -v l="$badges" '
    sub(/<div class=.docs.><h1>/, "") {
      print "<div class=\"docs\">" l "<h1>" $0
      next
    }
    1' "$f" > "$f.tmp"
  mv "$f.tmp" "$f"
done

echo $html
open $html
