#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
hi() { 
  clear
  echo -ne "\033[1;33m"
  cat<<-'EOF'
  
  '(the 
     (parentheses 
       (are (the 
         point)))) 

EOF
  echo -ne "\033[0m"
  echo "Short cuts:"
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}

here="$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )"

alias h="history"
alias ls="ls -G"
alias emacs="emacs -nw -q -l ../etc/doteditrc"
alias lisp="rlwrap sbcl --noinform "

export BASH_SILENCE_DEPRECATION_WARNING=1
export PATH="$PWD:/opt/homebrew/bin:$PATH"

isp() {
  f=$1
  shift
  $(which sbcl) --noinform --script $f  $* 2>&1 | less
}

there() { cd $1; basename `pwd`; }
PROMPT_COMMAND='echo -ne "🆑  $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(there ..)/$(there .):\!\e[m ▶ "'
hi
