#!/usr/bin/env bash

noPara1()  { gawk '
  BEGIN {RS=""; FS="\n"}
  NR==1 { next }
        { print($0 "\n")  }' 
}

classify() { gawk '
  /^; /  { print "DOC " $0; next;}
         { print "CODE "$0}' 
}

apply() { gawk '
  BEGIN {top=1}
      { now=$1
        gsub(/(DOC |CODE )/,"");
        apply(now,b4,last) 
        last=$0
        b4=now} 
END   { apply(now,b4,last)
;        if (now=="CODE") print "```" 
}

function apply(now,b4,last) {
  gsub(/^; /,"",last)
  if  (now==b4)  
     print(last)
  else {
   if (last !~ /^[ \t]*$/) last=last "\n"
   if (now=="CODE") {printf(last); print"\n```lisp"}
   if (now=="DOC")  {printf(last)
                    if (!top)   print"```\n" }
                    top=0}}' 
}


one() {
  f=${1%.*}
  shift
  title="$f: $*"
  (cat<<EOF
---
title: "$title"
---

EOF
  cat $f.lisp | noPara1 | classify  | apply) > ../docs/$f.md
}

for i in *.lisp
 do
   one $i
 done
