#!/usr/bin/env bash

noPara1()  { gawk '
  BEGIN {RS=""; FS="\n"}
  NR==1 { next }
        { print($0 "\n")  }' 
}

classify() { gawk '
  END    { exit }
  /^; /  { print "DOC " $0; next;}
         { print "CODE " $0}' 
}

ends() { gawk '{N[NR]=$0}
  END { if (N[NR-1]=="```lisp") N[NR-1]=""
        for(i=1;i<=NR;i++) print N[i] }'
}
apply() { gawk '
  BEGIN {top=1}
      { now=$1
        gsub(/(DOC |CODE )/,"");
        apply(now,b4,last) 
        last=$0
        b4=now} 
END   { apply(now,b4,last) }

function apply(now,b4,last) {
  gsub(/^; /,"",last)
  if  (now==b4)  
     print(last)
  else {
   if (last !~ /^[ \t]*$/) last=last "\n"
   if (now=="CODE") {printf(last); print"\n```lisp"}
   if (now=="DOC")  {printf(last)
                    if (!top)   print"```\n" }
                    top=0}}' 
}

one() {
  f=${1%.*}
  shift
  title="$f: $*"
  (cat<<EOF
---
title: "$title"
---

EOF
  cat $f.lisp | 
  noPara1 | 
  classify  |  apply | ends) > ../docs/$f.md 

}

for i in *.lisp
   do
     one $i
   done
