#!/usr/bin/env bash
############ paths
web="https://raw.githubusercontent.com/timm/lisp/master/espy"
Espy=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )

############# assert dirs exist
mkdir -p $Espy/etc
chmod +x $Espy/ell

############# ensure files exist
f=etc/tmux-conf; [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=etc/vimrc;     [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=etc/gitignore; [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=gitignore;     [ -f "$Espy/.$f" ] || cp $Espy/etc/$f $Espy/.$f

git add $Espy/etc/* $Espy/.gitignore

############## aliases
alias espy="lisp espy.lisp"
alias gp="git add *; git commit -am saving; git push; git status"
alias ls="ls -G"
alias repl="rlwrap sbcl --noinform "
alias tmux="$(which tmux) -f $Espy/etc/tmux-conf "
alias vi="vim -u $Espy/etc/vimrc "
alias vims="vim +PluginInstall +qall"         
############## tricks
lisp() { 
  f=$(basename $1 .lisp).lisp
  shift
  sbcl --noinform --script $f  $* 2> >(gawk '{print} /^5:/ {exit}') 
} 

here() { cd $1; basename `pwd`; }

hello() {
  clear
  tput bold; tput setaf 32; cat <<-'EOF'
   .-.
  (o o)  There is no escape from...
  ( O )    sH ELL !!!
   \   \      ver1 
    `~~~'
EOF
  tput sgr0
  tput bold; tput setaf 0
  awk '/^alias/ {print $0}'   $Espy/ell
  echo ""
  tput sgr0
}

mytmux() {
  session=$RANDOM
  Tmux=$(which tmux)
  $Tmux start-server
  sleep 1
  $Tmux new-session -d -s $session  
  $Tmux send-keys ". $Espy/ell"  C-m  "sleep 0.5; clear; vi espy.lisp" C-m

  $Tmux splitw -h -p 20
  $Tmux selectp -t 1
  $Tmux send-keys ".  $Espy/ell"  C-m  "clear; hello" C-m

  $Tmux splitw -v  -p 5
  $Tmux selectp -t 2
  $Tmux send-keys ".  $Espy/ell"  C-m  "htop"  C-m

  $Tmux attach-session -t $session
}

startup() {
  if [ ! -d "$HOME/.vim/bundle" ]; then
     git clone https://github.com/VundleVim/Vundle.vim.git \
           ~/.vim/bundle/Vundle.vim
     vims
  fi
  [ -z "$TMUX" ] && mytmux
}
############### prompt
PROMPT_COMMAND='echo -ne "👻 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'


[[ $1 == "-s" ]] && startup
