#!/etc/bin/env bash
web="https://raw.githubusercontent.com/timm/lisp/master/espy"
Espy=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
mkdir -p $Espy/etc

f=etc/tmux-conf; [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=etc/vimrc;     [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=etc/gitignore; [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=gitignore;     [ -f "$Espy/.$f" ] || cp $Espy/etc/$f $Espy/.$f

git add $Espy/etc/* $Espy/.gitignore

alias repl="rlwrap sbcl --noinform "
alias ls="ls -G"
alias gp="git add *; git commit -am saving; git push; git status"
alias vi="vim -u $Espy/etc/vimrc "
alias tmux="$(which tmux) -f $Espy/etc/tmux-conf "

lisp() { 
  f=$(basename $1 .lisp).lisp
  shift
  sbcl --noinform --script $f  $* 2> >(gawk '{print} /^5:/ {exit}') 
} 

here() { cd $1; basename `pwd`; }


PROMPT_COMMAND='echo -ne "👽 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
