#!/etc/bin/env bash
web="https://raw.githubusercontent.com/timm/lisp/master/espy"
Espy=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
mkdir -p $Espy/etc

want=etc/tmux-conf; [ -f "$Espy/$want" ] || wget -q -O $Espy/$want $web/$want
want=etc/vimrc;     [ -f "$Espy/$want" ] || wget -q -O $Espy/$want $web/$want

alias repl="rlwrap sbcl --noinform "
alias ls="ls -G"
alias gp="git add *; git commit -am saving; git push; git status"
alias vi="vim -u $Espy/etc/vimrc "
alias tmux="$(which tmux) -f $Espy/etc/tmux-conf "

lisp() { 
  f=$(basename $1 .lisp).lisp
  shift
  sbcl --noinform --script $f  $* 2> >(gawk '{print} /^5:/ {exit}') 
} 

here() { cd $1; basename `pwd`; }


PROMPT_COMMAND='echo -ne "👽 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
